Repository 047pegasus/devism, pull requests merged in 2023-10, with the labels that each got.

#8 Created a basic CRUD operation API
  .idea/.gitignore
  .idea/devism.iml
  .idea/discord.xml
  .idea/modules.xml
  .idea/vcs.xml
  Shashwat_Singh/CRUD_API/API.js
  Shashwat_Singh/Contributor.txt
Labels: hacktoberfest-accepted

#13 React Dashboard Appliaction Page
  Saurbh_kumar/Contributor.txt
  Saurbh_kumar/react-dashboard-app/.eslintrc.cjs
  Saurbh_kumar/react-dashboard-app/.gitignore
  Saurbh_kumar/react-dashboard-app/README.md
  Saurbh_kumar/react-dashboard-app/index.html
  Saurbh_kumar/react-dashboard-app/package-lock.json
  Saurbh_kumar/react-dashboard-app/package.json
  Saurbh_kumar/react-dashboard-app/public/vite.svg
  Saurbh_kumar/react-dashboard-app/src/App.css
  Saurbh_kumar/react-dashboard-app/src/App.jsx
  Saurbh_kumar/react-dashboard-app/src/Header.jsx
  Saurbh_kumar/react-dashboard-app/src/Home.jsx
  Saurbh_kumar/react-dashboard-app/src/Sidebar.jsx
  Saurbh_kumar/react-dashboard-app/src/assets/react.svg
  Saurbh_kumar/react-dashboard-app/src/main.jsx
  Saurbh_kumar/react-dashboard-app/vite.config.js
Labels: hacktoberfest-accepted

#21 Unemployment Dataset analysis
  Ashish/Unemployment Analysis.ipynb
Labels: hacktoberfest-accepted

#36 Project 2-KBC game
  Dhruv_Jain/python_KBC/KBC.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#39 Enhancement : Updated Reame.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
